### ISSUE TITLE
Deploying running twice

### ISSUE THREAD

**Issue by nab911** [zodern/mup-aws-beanstalk#91]
Our deploys are working, they are just taking up to an hour because it runs the entire Test instance, check, termination sequence twice. You can see the two distinct sequences starting at the line 

> Immutable deployment policy enabled. Launching one instance with the new settings to verify health.

After looking through the code, it seems as if the process is as follows:
Mup deploy steps:

1. Build bundle...
2. Uploading bundle
3. Creating Version
4. Configuring Beanstalk Environment
     - One deploy is here
5. Deploying new version
     - Second deploy is here
6. App is running at ENVIRONMENT_NAME

Below are the relevant portion of the logs.

```
...
Uploaded 100%
  Finishing upload. This could take a couple minutes
=> Creating Version
=> Configuring Beanstalk Environment
ebconfig for long env vars
  Updated Environment
=> Waiting for Beanstalk Environment to finish updating
  Env Event: Immutable deployment policy enabled. Launching one instance with the new settings to verify health.
  Env Event: Created temporary auto scaling group awseb-e-2jjkrww7pa-immutable-stack-AWSEBAutoScalingGroup-484HDHN0V2O9.
  Env Event: Added instance [i-0c52dbbd1261ea836] to your environment.
  Env Event: Environment health has transitioned from Ok to Info. Configuration update in progress on 1 instance. 0 out of 1 instance completed (running for 2 minutes).
  Env Event: Waiting for instance(s) (i-0c52dbbd1261ea836) to pass health checks.
  Env Event: Adding new instance(s) (i-0c52dbbd1261ea836) to the load balancer.
  Env Event: Test instance passed health checks. Launching remaining new instances.
  Env Event: Added instance [i-0c3804b4a6bf7c46c] to your environment.
  Env Event: Successfully launched all instances.
  Env Event: Waiting for instance(s) (i-0c3804b4a6bf7c46c,i-0c52dbbd1261ea836) to pass health checks.
  Env Event: Detached new instance(s) from temporary auto scaling group awseb-e-2jjkrww7pa-immutable-stack-AWSEBAutoScalingGroup-484HDHN0V2O9.
  Env Event: Attached new instance(s) to the permanent auto scaling group awseb-e-2jjkrww7pa-stack-AWSEBAutoScalingGroup-1QB18GZELHCBJ.
  Env Event: Starting post-deployment configuration on new instances.
  Env Event: Waiting for post-deployment configuration to complete.
  Env Event: Updating environment mup-env-hive-meteor--beta's configuration settings.
  Env Event: Deployment succeeded. Terminating old instances and temporary Auto Scaling group.
  Env Event: Removed instance [i-04a8ba8d2787d423c] from your environment.
  Env Event: Environment health has transitioned from Info to Warning. 3 instances online is below Auto Scaling group desired capacity 4. Configuration update in progress. 2 out of 2 instances completed (running for 16 minutes).
  Env Event: Environment health has transitioned from Warning to Info. Configuration update in progress. 2 out of 2 instances completed (running for 16 minutes).
  Env Event: Removed instance [i-049b2dd2eb826a9f1] from your environment.
=> Deploying new version
=> Waiting for Beanstalk Environment to finish updating
  Env Event: Environment health has transitioned from Info to Ok. Configuration update completed 55 seconds ago and took 19 minutes.
  Env Event: Immutable deployment policy enabled. Launching one instance with the new settings to verify health.
  Env Event: Created temporary auto scaling group awseb-e-2jjkrww7pa-immutable-stack-AWSEBAutoScalingGroup-1DOZVGXLRJM6X.
  Env Event: Added instance [i-0152d4cf501bdb571] to your environment.
  Env Event: Environment health has transitioned from Ok to Info. Application update in progress on 1 instance. 0 out of 1 instance completed (running for 83 seconds).
  Env Event: Adding new instance(s) (i-0152d4cf501bdb571) to the load balancer.
  Env Event: Test instance passed health checks. Launching remaining new instances.
  Env Event: Added instance [i-00d467cd19b16b297] to your environment.
  Env Event: Adding new instance(s) (i-00d467cd19b16b297) to the load balancer.
  Env Event: Successfully launched all instances.
  Env Event: Waiting for instance(s) (i-00d467cd19b16b297,i-0152d4cf501bdb571) to pass health checks.
  Env Event: Detached new instance(s) from temporary auto scaling group awseb-e-2jjkrww7pa-immutable-stack-AWSEBAutoScalingGroup-1DOZVGXLRJM6X.
  Env Event: Attached new instance(s) to the permanent auto scaling group awseb-e-2jjkrww7pa-stack-AWSEBAutoScalingGroup-1QB18GZELHCBJ.
  Env Event: Starting post-deployment configuration on new instances.
  Env Event: Waiting for post-deployment configuration to complete.
  Env Event: Deployment succeeded. Terminating old instances and temporary Auto Scaling group.
  Env Event: Removed instance [i-0c3804b4a6bf7c46c] from your environment.
  Env Event: Environment health has transitioned from Info to Warning. 3 instances online is below Auto Scaling group desired capacity 4. Application update in progress. 2 out of 2 instances completed (running for 15 minutes).
  Env Event: Environment health has transitioned from Warning to Info. Application update in progress. 2 out of 2 instances completed (running for 16 minutes).
  Env Event: Removed instance [i-0c52dbbd1261ea836] from your environment.
App is running at mup-env-hive-meteor--beta.pkdb2hbxe7.us-east-1.elasticbeanstalk.com
=> Finding old versions
=> Removing old versions
=> Updating Beanstalk SSL Config
...
```

**Comment by nab911** [comment]
@zodern any ideas on this one?

**Comment by AleF1** [comment]
Same issue here with Immutable policy... Maybe that's the issue?

**Comment by AleF1** [comment]
> Same issue here with Immutable policy... Maybe that's the issue?

Fixed with the following config:

customBeanstalkConfig: [
            {
                namespace: 'aws:autoscaling:asg',
                option: 'Cooldown',
                value: '300'
            },
            {
            namespace: 'aws:elasticbeanstalk:command',
            option: 'DeploymentPolicy',
            value: 'Immutable'
            },
            {
            namespace: 'aws:autoscaling:updatepolicy:rollingupdate',
            option: 'RollingUpdateType',
            value: 'Immutable'
            },
        ]
    },

**Comment by nab911** [comment]
We already had the Immutable settings for both DeploymentPolicy and RolingUpdateType. I can test the cooldown but it looks like the default value is already 300s

**Comment by AleF1** [comment]
> We already had the Immutable settings for both DeploymentPolicy and RolingUpdateType. I can test the cooldown but it looks like the default value is already 300s

my bad... indeed, I have the error again (it was just one lucky deploy)

**Comment by AleF1** [comment]
any updates on this matter?

**Comment by alexkyen** [comment]
@AleF1 chatted with @zodern about this and we have an open PR to fix it.

**Comment by gerwinbrunner** [comment]
@AleF1 @nab911  Did you find a solution? 
I still get the same double deploy issue with the current 0.6.4 version 

```
    customBeanstalkConfig: [
      {
        namespace: "aws:elasticbeanstalk:command",
        option: "DeploymentPolicy",
        value: "Immutable",
      },
      {
        namespace: "aws:autoscaling:updatepolicy:rollingupdate",
        option: "RollingUpdateType",
        value: "Immutable",
      },
      {
        namespace: "aws:elasticbeanstalk:command",
        option: "BatchSize",
        value: "100",
      },
    ],
```

**Comment by alexkyen** [comment]
@gerwinbrunner check out #114, should fix it - we've been running a fork with that code for many months now.

**Comment by gerwinbrunner** [comment]
We still have the double deploy issue :(

@alexkyen 
can you share your `customBeanstalkConfig` please?

**Comment by gerwinbrunner** [comment]
It might be related to this issue:
https://github.com/zodern/mup-aws-beanstalk/issues/119

**Comment by zodern** [comment]
The fix will be included in 0.7. Instructions for trying the beta are in #142.
